"""ChArUco board detector for D456 extrinsic calibration.

Detects a printed ChArUco board in an image and returns the board's
6-DoF pose in the camera frame. This is the first stage of the D456 →
robot-base extrinsic calibration pipeline (see d456_perception_design.md
§1.1). Hardware-free; tested via synthetic images generated by
``cv2.aruco.CharucoBoard.generateImage()``.

Convention notes
----------------
- Image input is treated as BGR (OpenCV default) or grayscale.
- ``BoardPose.to_4x4_matrix()`` returns ``T_camera_board`` — the homogeneous
  transform that maps a 3D point expressed in the *board* frame into the
  *camera* frame: ``P_camera = T_camera_board @ P_board``.
- World-frame extrinsic (``T_world_camera``) is intentionally NOT computed
  here. World origin = 책상 가운데 placement is performed on 5/12 with a
  measured board pose; see README §"Next steps".

OpenCV API used
---------------
This module targets the OpenCV 4.7+ ArUco rewrite:
- ``cv2.aruco.CharucoBoard((cols, rows), squareLen, markerLen, dictionary)``
  (4.6 이전 ``CharucoBoard_create`` 폐기)
- ``cv2.aruco.CharucoDetector(board)`` for combined marker+corner detection
- ``board.matchImagePoints(corners, ids)`` + ``cv2.solvePnP`` for pose
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import cv2
import numpy as np


# ---- Board parameters (인쇄된 보드와 정확히 일치해야 함) ----
# TODO: 인쇄 PDF 메타정보 검증 후 수정 — 현재는 spec §1.1 기본 가정
# 인쇄된 보드: 5 rows × 7 columns, checker 40mm. Marker 30mm는 ChArUco
# 규약(checker의 0.7~0.8배)에서 도출한 가정. Dictionary는 사이트 기본값.
DICTIONARY_ID: int = cv2.aruco.DICT_4X4_50
CHECKER_ROWS: int = 5      # checker 가로줄 개수
CHECKER_COLS: int = 7      # checker 세로줄 개수
CHECKER_SIZE: float = 0.040  # m, 한 변 길이
MARKER_SIZE: float = 0.030   # m, ArUco 마커 한 변 길이

# 코너가 이보다 적게 검출되면 pose 신뢰 안 함 (solvePnP 최소 4개지만 안전 마진).
MIN_CORNERS_FOR_POSE: int = 6


# OpenCV가 받아들이는 distortion vector 길이 (rational/thin-prism/tilted 모델 포함).
_VALID_DIST_LENGTHS = (4, 5, 8, 12, 14)


@dataclass
class BoardPose:
    """6-DoF board pose expressed in the camera frame.

    Attributes
    ----------
    rvec : np.ndarray, shape (3,)
        Rodrigues rotation vector (camera ← board).
    tvec : np.ndarray, shape (3,)
        Translation vector in meters (camera ← board).
    n_corners_detected : int
        Number of ChArUco interior corners used for the PnP solve.
    reprojection_rms_px : float
        RMS reprojection error of the detected corners back into the image,
        in pixels. Sanity metric for detection quality.
    """

    rvec: np.ndarray
    tvec: np.ndarray
    n_corners_detected: int  # 실제 PnP 에 사용된 점 수 (len(obj_points) after matchImagePoints)
    reprojection_rms_px: float

    def to_4x4_matrix(self) -> np.ndarray:
        """Return ``T_camera_board`` as a 4x4 homogeneous matrix.

        Maps a board-frame point ``P_b = (X, Y, Z, 1)`` to the camera frame:
        ``P_c = T @ P_b``.
        """
        T = np.eye(4, dtype=np.float64)
        R, _ = cv2.Rodrigues(self.rvec.reshape(3, 1).astype(np.float64))
        T[:3, :3] = R
        T[:3, 3] = self.tvec.astype(np.float64).reshape(3)
        return T


def _build_board() -> Tuple[cv2.aruco.Dictionary, cv2.aruco.CharucoBoard]:
    # OpenCV는 (cols, rows) 순서를 받음. spec의 "5 rows × 7 cols"는 (7, 5).
    dictionary = cv2.aruco.getPredefinedDictionary(DICTIONARY_ID)
    board = cv2.aruco.CharucoBoard(
        (CHECKER_COLS, CHECKER_ROWS),
        CHECKER_SIZE,
        MARKER_SIZE,
        dictionary,
    )
    return dictionary, board


_DICT, _BOARD = _build_board()


def get_board() -> cv2.aruco.CharucoBoard:
    """Expose the configured board (used by tests and offline rendering)."""
    return _BOARD


def get_dictionary() -> cv2.aruco.Dictionary:
    return _DICT


def _validate_inputs(
    image: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
) -> Tuple[np.ndarray, np.ndarray]:
    if image is None:
        raise ValueError("image is None")
    if not isinstance(image, np.ndarray):
        raise ValueError(f"image must be np.ndarray; got {type(image).__name__}")
    if image.ndim not in (2, 3):
        raise ValueError(
            f"image must have shape (H,W) or (H,W,3); got {image.shape}"
        )
    if image.ndim == 3 and image.shape[2] != 3:
        raise ValueError(
            f"3-channel image must have channels-last; got {image.shape}"
        )

    K = np.asarray(camera_matrix, dtype=np.float64)
    if K.shape != (3, 3):
        raise ValueError(f"camera_matrix must be 3x3; got shape {K.shape}")

    dist = np.asarray(dist_coeffs, dtype=np.float64).reshape(-1)
    if dist.size not in _VALID_DIST_LENGTHS:
        raise ValueError(
            f"dist_coeffs length must be in {_VALID_DIST_LENGTHS}; got {dist.size}"
        )
    return K, dist


def _to_gray(image: np.ndarray) -> np.ndarray:
    if image.ndim == 2:
        return image
    return cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)


def _reprojection_rms(
    obj_points: np.ndarray,
    img_points: np.ndarray,
    rvec: np.ndarray,
    tvec: np.ndarray,
    K: np.ndarray,
    dist: np.ndarray,
) -> float:
    projected, _ = cv2.projectPoints(obj_points, rvec, tvec, K, dist)
    diff = projected.reshape(-1, 2) - img_points.reshape(-1, 2)
    return float(np.sqrt(np.mean(np.sum(diff * diff, axis=1))))


def detect_charuco(
    rgb_image: np.ndarray,
    camera_matrix: np.ndarray,
    dist_coeffs: np.ndarray,
) -> Optional[BoardPose]:
    """Detect the configured ChArUco board and return its pose in the camera frame.

    Parameters
    ----------
    rgb_image : np.ndarray
        BGR (H,W,3) or grayscale (H,W) uint8 image. **The parameter name
        ``rgb_image`` is kept for spec parity, but the implementation treats
        3-channel input as BGR** (OpenCV default — ``cv2.cvtColor`` uses
        ``COLOR_BGR2GRAY``). The caller is responsible for color-order
        consistency: ``pyrealsense2`` streams can be configured as ``rgb8``
        or ``bgr8`` — pass BGR. ChArUco detection is binary so channel-
        order swap rarely affects detection rate, but downstream debug
        renders or color-sensitive heuristics may be surprised.
    camera_matrix : np.ndarray, shape (3, 3)
        Pinhole intrinsic matrix.
    dist_coeffs : np.ndarray
        Distortion coefficients in OpenCV order (length 4/5/8/12/14).

    Returns
    -------
    Optional[BoardPose]
        A ``BoardPose`` if at least ``MIN_CORNERS_FOR_POSE`` charuco corners
        survive the full pipeline (detection + matchImagePoints + solvePnP).
        ``None`` on any pipeline failure — including OpenCV exceptions
        thrown by ``solvePnP`` (caught and converted to ``None``).

    Raises
    ------
    ValueError
        If ``rgb_image`` / ``camera_matrix`` / ``dist_coeffs`` shapes are
        invalid. Detection / pose-solve failure itself does *not* raise.
    """
    K, dist = _validate_inputs(rgb_image, camera_matrix, dist_coeffs)
    gray = _to_gray(rgb_image)

    detector = cv2.aruco.CharucoDetector(_BOARD)
    charuco_corners, charuco_ids, _marker_corners, _marker_ids = detector.detectBoard(gray)

    if charuco_corners is None or charuco_ids is None:
        return None
    if int(len(charuco_ids)) < MIN_CORNERS_FOR_POSE:
        return None

    obj_points, img_points = _BOARD.matchImagePoints(charuco_corners, charuco_ids)
    if obj_points is None or img_points is None:
        return None
    n_used = int(len(obj_points))
    # img_points 길이 mismatch 는 정상 OpenCV 흐름에서는 안 나오지만
    # solvePnP assertion 으로 raise 되기 전에 방어적으로 거름. (Codex review 5/11)
    if n_used < MIN_CORNERS_FOR_POSE or n_used != int(len(img_points)):
        return None

    # ITERATIVE 는 OpenCV solvePnP 의 현재 default. flag 미명시 시 default 변동
    # 위험을 막기 위해 명시 — Codex review 5/11. planar target 에 IPPE 가 더
    # 정확할 수 있지만 OpenCV estimatePoseCharucoBoard 내부 구현과 동일한
    # ITERATIVE 를 사용해 거동 일치 유지.
    try:
        success, rvec, tvec = cv2.solvePnP(
            obj_points, img_points, K, dist,
            flags=cv2.SOLVEPNP_ITERATIVE,
        )
    except cv2.error:
        return None
    if not success:
        return None

    rms = _reprojection_rms(obj_points, img_points, rvec, tvec, K, dist)

    return BoardPose(
        rvec=rvec.reshape(3).astype(np.float64),
        tvec=tvec.reshape(3).astype(np.float64),
        n_corners_detected=n_used,
        reprojection_rms_px=rms,
    )


# ---- 5/12 실측 후 작성 예정 ----
# def board_to_world_transform(board_pose: BoardPose) -> np.ndarray:
#     """Compose ``T_world_camera`` from a board pose, given the board is
#     placed at the world origin (책상 가운데).
#
#     의도적으로 stub 미구현. identity 반환 stub 은 5/12 실측 시 silent
#     하게 잘못된 좌표를 흘려보낼 위험이 큼 (Codex review 5/11 지적).
#     보드 placement 측정 결과(보드 ↔ 책상 가운데 위치/회전)가 확정된
#     이후에 본 함수 구현. README 의 "Next steps" 참조.
#     """
#     raise NotImplementedError("Implement after 5/12 board placement measurement")
